// Mocks generated by Mockito 5.3.2 from annotations
// in mafia_game_front/Services/user_service.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:grpc/grpc.dart' as _i3;
import 'package:image_picker/image_picker.dart' as _i6;
import 'package:mafia_game_front/Proto/mafia.pbgrpc.dart' as _i2;
import 'package:mafia_game_front/Services/user_service.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeaccountClient_0 extends _i1.SmartFake implements _i2.accountClient {
  _FakeaccountClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponseFuture_1<R> extends _i1.SmartFake
    implements _i3.ResponseFuture<R> {
  _FakeResponseFuture_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProfilePictureUrl_2 extends _i1.SmartFake
    implements _i2.ProfilePictureUrl {
  _FakeProfilePictureUrl_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i4.UserService {
  @override
  _i2.accountClient get accountClientInstance => (super.noSuchMethod(
        Invocation.getter(#accountClientInstance),
        returnValue: _FakeaccountClient_0(
          this,
          Invocation.getter(#accountClientInstance),
        ),
        returnValueForMissingStub: _FakeaccountClient_0(
          this,
          Invocation.getter(#accountClientInstance),
        ),
      ) as _i2.accountClient);
  @override
  _i3.ResponseFuture<_i2.RegisterResponse> createUser(
    String? email,
    String? username,
    String? password,
    String? repeatPassword,
    String? profileImageName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [
            email,
            username,
            password,
            repeatPassword,
            profileImageName,
          ],
        ),
        returnValue: _FakeResponseFuture_1<_i2.RegisterResponse>(
          this,
          Invocation.method(
            #createUser,
            [
              email,
              username,
              password,
              repeatPassword,
              profileImageName,
            ],
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_1<_i2.RegisterResponse>(
          this,
          Invocation.method(
            #createUser,
            [
              email,
              username,
              password,
              repeatPassword,
              profileImageName,
            ],
          ),
        ),
      ) as _i3.ResponseFuture<_i2.RegisterResponse>);
  @override
  _i5.Future<_i2.ProfilePictureUrl> uploadProfilePicture(_i6.XFile? image) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadProfilePicture,
          [image],
        ),
        returnValue:
            _i5.Future<_i2.ProfilePictureUrl>.value(_FakeProfilePictureUrl_2(
          this,
          Invocation.method(
            #uploadProfilePicture,
            [image],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.ProfilePictureUrl>.value(_FakeProfilePictureUrl_2(
          this,
          Invocation.method(
            #uploadProfilePicture,
            [image],
          ),
        )),
      ) as _i5.Future<_i2.ProfilePictureUrl>);
}
